TrainingArguments:
    output_dir: './output/'
    save_total_limit: 5
    save_steps: 200
    seed: 42

    num_train_epochs: 3
    learning_rate: 2e-5
    per_device_train_batch_size: 8
    per_device_eval_batch_size: 8

    weight_decay: 0
    lr_scheduler_type: 'linear'
    gradient_accumulation_steps: 1
    
    warmup_ratio: 0.0
    warmup_steps: 0

    logging_dir: './logs'
    logging_steps: 100

    evaluation_strategy: 'steps'
    eval_steps: 500
    load_best_model_at_end: True

    do_train: True
    do_eval: True

    fp16: True
    fp16_opt_level: 'O1'

    label_smoothing_factor: 0.0

    report_to: 'wandb'
    run_name: 'baseline'


ModelArguments:
    model_name_or_path: 'klue/bert-base'
    config_name: null
    tokenizer_name: null


DataTrainingArguments:
    dataset_name: '../data/train_dataset'
    overwrite_cache: False
    preprocessing_num_workers: null

    max_seq_length: 384
    pad_to_max_length: False
    doc_stride: 128
    max_answer_length: 30
    
    eval_retrieval: True
    num_clusters: 64
    top_k_retrieval: 10
    use_faiss: False